apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU$  # ← Use your actual full base64 CA data
    server: https://127.0.0.1:57827                    # ← Match the Minikube API server port
  name: minikube
contexts:
- context:
    cluster: minikube
    user: jenkins
  name: jenkins-context
current-context: jenkins-context
kind: Config
preferences: {}
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJFVmJ5Rk5ESXRLeEJpMDVoZm9MSURUVmN4YUp2d0dtNzh4ZENhTDBseXcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUxMDM5NDQyLCJpYXQiOjE3NTEwMzU4NDIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiODhhYjEwN2UtYTgwZS00MDQwLWI2YzMtNzZkNGEzNzQ3ODEzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJqZW5raW5zLXNhIiwidWlkIjoiOWVjNTcwMWQtNWZlOC00ZWRlLWFjZmUtNTI2MDdjZDI3OGQzIn19LCJuYmYiOjE3NTEwMzU4NDIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpqZW5raW5zLXNhIn0.EFXhZaGy-Ll8ZDP8yGbTkqafsvZEtLOofQ-xQ_duXy0f-LDq8KDvPKLN1oZm5lVOy0ipZ1dsdIaJJMAx5v6p8cAgQSJlxxnCrRTZwGiY6X6F_1fiA5EHPvikC2lyR4pOmuWvH6oJH8n_pEGmD1KXNyQN0teypy8vQF3EmTeYEeFB-BEDBE-RuTVI8FrxgqXxPBS54XVt0m0zI8abyXb5O1iVncnE9E5Naot6aaUpoRt4BDdMLUN5VyMF3KRxjCFrVt7FGPCvUx-okJJP34UFOsFFmUnZd9Ann-w18oqwbET1XGaE9FLkxPt7sjTLtwdNeKbqKbtVhiGshokHRpn5iQ
