apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-webapp
  template:
    metadata:
      labels:
        app: devops-webapp
    spec:
      containers:
      - name: devops-webapp
        image: amar0126/devops-webapp:latest
        ports:
        - containerPort: 3000
