apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: devops-webapp-service
spec:
  type: NodePort
  selector:
    app: devops-webapp
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30036
=======
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
>>>>>>> ad3f53c (✅ Update Jenkinsfile and kubeconfig)
